AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  lambdaTest:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs12.x
      CodeUri: .
      Description: ''
      MemorySize: 1024
      Timeout: 60
      Role: 'arn:aws:iam::319199529121:role/service-role/lambdaTest-role-jkb31pwg'
      Layers:    
        - 'arn:aws:lambda:us-east-1:764866452798:layer:chrome-aws-lambda:10'
